<a href="https://colab.research.google.com/github/MarihRodrigues/ONE-AI-FOR-TECH/blob/main/Aula3e4_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Estrutura de repeticao loop : "for"

In [ ]:
dict_desafio = [
    {"nome": "Maria Silva", "média": 8.9},
    {"nome": "João Santos", "média": 7.5},
    {"nome": "Ana Oliveira", "média": 4.2},
    {"nome": "Pedro Costa", "média": 1.4}
]

In [ ]:
n = 0

while n < len(dict_desafio):
  print(dict_desafio[n])

  n += 1

{'nome': 'Maria Silva', 'média': 8.9}
{'nome': 'João Santos', 'média': 7.5}
{'nome': 'Ana Oliveira', 'média': 4.2}
{'nome': 'Pedro Costa', 'média': 1.4}

In [ ]:
for elemento in dict_desafio:
  print(elemento)

{'nome': 'Maria Silva', 'média': 8.9}
{'nome': 'João Santos', 'média': 7.5}
{'nome': 'Ana Oliveira', 'média': 4.2}
{'nome': 'Pedro Costa', 'média': 1.4}

In [ ]:
for n in range(5):
  print(n)

0
1
2
3
4

In [ ]:
for n in range(2,7):
  print(n)

2
3
4
5
6

In [ ]:
for n in range(2,7,2):
  print(n)

2
4
6

In [ ]:
for n in range(2,7,3):
  print(n)

2
5

In [ ]:
pessoa = {
    "nome": "Fabricio",
    "idade": 19,
    "altura": "1.87"
}
print(pessoa)

{'nome': 'Fabricio', 'idade': 19, 'altura': '1.87'}

In [ ]:
for chave in pessoa:
  print(chave)

nome
idade
altura

In [ ]:
pessoa.items()

dict_items([('nome', 'Fabricio'), ('idade', 19), ('altura', '1.87')])

In [ ]:
pessoa.keys()

dict_keys(['nome', 'idade', 'altura'])

In [ ]:
pessoa.values()

dict_values(['Fabricio', 19, '1.87'])

In [ ]:
for chave, valor in pessoa.items():
  print(f"A chave e {chave} e o valor e {valor}.")

A chave e nome e o valor e Fabricio.
A chave e idade e o valor e 19.
A chave e altura e o valor e 1.87.

In [ ]:
for n in range(11):
  if n%2 == 0:
    print(n)

0
2
4
6
8
10

In [ ]:
for n in range(11):
  if n%3 == 0:
    print(n)

0
3
6
9

# Funcoes

In [ ]:
texto1 = "   Fabricio CARRaro  da alura"
texto2 = "mArIA   aNA    alvaRes  cabrAL"
texto3 = "    anA caroLINa    FerreirA"
texto4 = "rObertO    carLOS    oliveiRa"

In [ ]:
texto1.split()

['Fabricio', 'CARRaro', 'da', 'alura']

In [ ]:
len(texto1.split())

4

In [ ]:
def escreve_texto_corretamente(texto):
  texto_novo = texto.upper()
  lista_de_palavras = texto_novo.split()
  nome_final = " ".join(lista_de_palavras)
  return nome_final

In [ ]:
escreve_texto_corretamente(texto1)

FABRICIO CARRARO DA ALURA

In [ ]:
escreve_texto_corretamente(texto2)

MARIA ANA ALVARES CABRAL

In [ ]:
escreve_texto_corretamente(texto3)

ANA CAROLINA FERREIRA

In [ ]:
def escreve_texto_corretamente_alternativa(texto):
  print(" ".join(texto.upper().split()))

In [ ]:
escreve_texto_corretamente_alternativa(texto2)

MARIA ANA ALVARES CABRAL

In [ ]:
salas_de_aula = ["Sala 1", "Sala 2", "Sala 3"]

In [ ]:
aloca_aluno_em_salas(texto1, salas_de_aula)

In [ ]:
import random

def aloca_alunos_em_salas(nome_do_aluno, lista_de_salas):
  sala_do_aluno = random.choice(lista_de_salas)

  dict_aluno = {
      "nome": nome_do_aluno,
      "sala": sala_do_aluno
  }
  print(dict_aluno)

In [ ]:
aloca_alunos_em_salas(texto1, salas_de_aula)

{'nome': '   Fabricio CARRaro  da alura', 'sala': 'Sala 2'}

In [111]:
nome_processado = escreve_texto_corretamente(texto1)
aloca_alunos_em_salas(nome_processado, ["Classe 1", "Classe 2", "Classe 3"])

{'nome': 'FABRICIO CARRARO DA ALURA', 'sala': 'Classe 3'}

Desafio:
<br>
1. Pedir pra uma IA gerar em Python uma lista de 20 emails.
2. Criar uma funcao que vai receber como argumento/parametro uma lista de emails, percorrer essa lista, e, para cada email da lista ela ira chamar a IA do gemini e pedir pra ela resumir pra voce todos os emails em apenas 1 linha, definindo o que essa pessoa queria no email.

### Reconfiguração da API do Gemini

As células de configuração da API foram removidas. Precisamos reconfigurá-las para que o modelo Gemini possa ser utilizado.

In [126]:
# Instale o SDK do Python para Gemini
!pip install -q -U google-generativeai

import google.generativeai as genai
from google.colab import userdata

# Carregue a chave de API do Gemini a partir dos segredos do Colab
# Usando 'GOOGLE_API_KEY' conforme o estado do kernel.
GOOGLE_API_KEY = userdata.get('gemini_key')
genai.configure(api_key=GOOGLE_API_KEY)

Agora, vamos inicializar o modelo generativo.

In [124]:
# Inicialize o modelo Gemini com 'gemini-1.0-pro'
gemini_model = genai.GenerativeModel('gemini-2.0-flash')

In [146]:
email_bodies = [

    {
        "assunto": "Reunião de alinhamento",
        "corpo": """Olá,

Gostaria de agendar uma reunião para alinharmos as próximas atividades do projeto.
Você teria disponibilidade amanhã às 14h? Caso esse horário não seja conveniente,
por favor, informe outro horário que funcione para você.

Fico no aguardo.

Atenciosamente,"""
    },
    {
        "assunto": "Confirmação de presença",
        "corpo": """Olá,

Estamos entrando em contato para confirmar sua presença no evento da próxima sexta-feira.
Por gentileza, responda este e-mail informando se poderá comparecer.

Obrigado!"""
    },
    {
        "assunto": "Solicitação de documentos",
        "corpo": """Prezados,

Para darmos continuidade ao processo, precisamos dos seguintes documentos:
- Documento de identidade;
- Comprovante de residência;
- CPF.

Solicitamos o envio até o final desta semana.

Atenciosamente,"""
    },
    {
        "assunto": "Atualização de sistema",
        "corpo": """Olá,

Informamos que nosso sistema passará por uma manutenção programada neste sábado,
das 22h às 02h. Durante esse período alguns serviços poderão ficar indisponíveis.

Agradecemos a compreensão."""
    },
    {
        "assunto": "Agradecimento pela parceria",
        "corpo": """Olá,

Gostaríamos de agradecer pela parceria e confiança em nossos serviços.
Esperamos continuar trabalhando juntos em novos projetos.

Conte sempre conosco!"""
    }
]

In [147]:
import google.generativeai as genai

def resumidor_de_emails(email_bodies):
  lista_de_resumos = []
  for numero, email in enumerate(email_bodies):
       # Usando o objeto gemini_model previamente inicializado
       resposta = gemini_model.generate_content(
           contents=f"""Vou te mandar o corpo de um
            e-mail. Quero que voce o resuma em apenas
             1 linha, passando o intuito daquele e-mail.
             Segue o e-mail: {email['corpo']}""" # Acessando o campo 'corpo' do dicionário
       )
       print(f"E-mail {numero + 1}: {resposta.text}")
       lista_de_resumos.append(f"E-mail {numero + 1}: {resposta.text}")
       print("-"*50)

  return lista_de_resumos

In [148]:
lista_resumos = resumidor_de_emails(email_bodies)

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.0-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 533.18ms

TooManyRequests: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-2.0-flash
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-2.0-flash
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-2.0-flash
Please retry in 11.014220791s.

In [149]:
!pip install -q groq

In [150]:
import os
os.environ["GROQ_API_KEY"] = userdata.get('groq')

In [151]:
from groq import Groq

client = Groq()
completion = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
      {
        "role": "user",
        "content": "Do que e feito o sol\n"
      },

    ],
    temperature=1,
    max_completion_tokens=2048,
    top_p=1,
    reasoning_effort="medium",
    stream=True,
    stop=None
)

for chunk in completion:
    print(chunk.choices[0].delta.content or "", end="")

**O que compõe o Sol?**

O Sol não é um sólido ou líquido como os objetos que vemos na Terra; ele é um enorme plasma—uma mistura de íons e elétrons em estado de alta temperatura e pressão. Quando falamos em “compostos” do Sol, estamos nos referindo à composição química (ou, mais tecnicamente, à composição elemental) do material que o constitui.

---

## 1. Proporções massuais

| Elemento | Porcentagem massal | Porcentagem por número de átomos |
|----------|--------------------|----------------------------------|
| Hidrogênio (H) | ~74 % | ~90 % |
| Hélio (He) | ~24 % | ~9 % |
| Metais (toda a matéria mais pesada que hélio) | ~2 % | < 1 % |

> **Obs.** “Metais” na astronomia incluem todos os elementos mais pesados que hélio: carbono, oxigênio, silício, ferro, etc. Eles são chamados de “metais” porque, em termos químicos, os elementos de transição e mais pesados se comportam de forma semelhante à de metais comuns.

### Por que essas proporções?

- **Hidrogênio**: o elemento mais abundante no universo. Os protótipos de estrelas nas nuvens interestelares são compostos majoritariamente por hidrogênio, e a maior parte do Sol (por massa) continua sendo hidrogênio.
- **Hélio**: resultado das primeiras explosões nucleares no Big Bang e da fusão contínua de hidrogênio no núcleo do Sol.
- **Metais**: formados em núcleos estelares mais antigos e espalhados pelo meio interestelar antes de se tornarem parte do nosso Sistema Solar.

---

## 2. Camadas e estado do material

1. **Núcleo (≈ 0 – 0,25 R⊙)**
   * Temperatura ~ 15  milhões de K
   * Pressão extremamente alta → hidrogênio ionizado, plasma denso.
   * Onde ocorre a fusão de H → He (via cadeia protão‑protão ou CNO).

2. **Zona de radiação (≈ 0,25 – 0,70 R⊙)**
   * Plasma ainda quente e denso.
   * Energia transportada principalmente por radiação (foton).

3. **Zona convectiva (≈ 0,70 – 1,0 R⊙)**
   * Temperatura menor, densidade menor → material quente sobe, frio desce.
   * Transporta energia para a superfície (fotossfera).

4. **Fotossfera**
   * Camada visível que vemos como a “superfície” do Sol.
   * Temperatura ~ 5.800 K – a região mais “visível” para a espectroscopia.

5. **Cromosfera e Corona**
   * Camadas externas do Sol, onde a temperatura sobe novamente (até milhões de K na corona).
   * A composição continua dominada por H e He, mas a ionização é muito alta (até H IV, He VI, etc.).

---

## 3. Como sabemos isso?

| Técnica | Como funciona | O que mede |
|---------|---------------|------------|
| **Espectroscopia solar** | Observa as linhas de absorção e emissão no espectro do Sol | Composição elemental (p. ex., linhas de H, He, Fe, etc.) |
| **Helioseismologia** | Analisa ondas de pressão que viajam pelo interior | Densidade, composição por profundidade, velocidade de rotação |
| **Modelos nucleares** | Calcula reações de fusão e produção de elementos | Distribuição de isotopos (p. ex., ³He, ⁴He) |

Essas metodologias combinadas dão uma visão muito detalhada da composição do Sol, que corresponde à composição média de nuvens moleculares que formaram o Sistema Solar há cerca de 4,6 bilhões de anos.

---

## 4. Pequenos detalhes curiosos

- **Fusão nuclear**: a energia que o Sol libera vem da conversão de ~ 4 kg de hidrogênio em ~ 3,5 kg de hélio e radiação (cerca de 0,7 % da massa total se transformando em energia, conforme a equação de Einstein \(E = mc^2\)).
- **Degradação de metais**: a pequena fração de metais (~2 % em massa) tem efeitos importantes, como a condução térmica e a geração de radiação eletromagnética na zona convectiva.
- **Metallicitade**: astronomos medem a “metallicitade” do Sol, geralmente designada como \([M/H]\). Para o Sol, \([M/H] = 0\) por definição, mas a “metallicitade solar” típica é \(\approx 1,5\%\) em massa.

---

## 5. Resumindo

O Sol é, em massa, composto principalmente por **hidrogênio (~74 %)** e **hélio (~24 %)**, com uma pequena, porém crucial, fração de **metais (~2 %)**. Todo esse material está em estado de plasma, distribuído em camadas que vão do núcleo quente e denso até a coronal quente e tenuífera. Essa composição foi determinada por observações espectroscópicas, estudo das ondas internas e modelos de fusão nuclear.

Se quiser saber mais detalhes (por exemplo, as abundâncias de cada elemento individual), pode consultar a literatura de abundâncias solares (e.g., Asplund et al. 2009) ou bases de dados como o *Atomic Spectra Database* (NSF) e *NIST*.

---

# Aula 4
## Lendo e escrevendo em arquivos usando Python

In [153]:
with open("lista_de_resumos.txt", "w", encoding="utf-8") as arquivo:
   for resumo in lista_resumos:
    arquivo.write(resumo + "\n")

NameError: name 'lista_resumos' is not defined

In [155]:
nova_lista_de_leitura = []
with open("lista_de_resumos.txt", "r", encoding="utf-8") as arquivo:
   for linha in arquivo:
    nova_lista_de_leitura.append(linha)

In [156]:
nova_lista_de_leitura

[]

In [157]:
conteudo = ""
with open("lista_de_resumos.txt", "r", encoding="utf-8") as arquivo:
  arquivo.read()

In [158]:
conteudo

''

In [159]:
nova_lista_de_leitura_2 = []

with open("lista_de_resumos.txt", "r", encoding="utf-8") as arquivo:
   nova_lista_de_leitura_2 = arquivo.readlines()

In [160]:
nova_lista_de_leitura_2

[]

## Manipulando dados com Pandas

In [161]:
import pandas as pd

In [162]:
df = pd.read_csv("/content/meu_csv.csv")

In [163]:
df

               Nome  Media
0         Ana Souza    8.5
1        Bruno Lima    7.2
2      Carla Mendes    9.1
3      Daniel Rocha    6.8
4     Eduarda Alves    8.9
5      Felipe Costa    5.7
6  Gabriela Martins    9.5
7    Henrique Silva    7.9
8  Isabela Ferreira    8.3
9      João Pereira    6.4

In [164]:
df.head()

            Nome  Media
0      Ana Souza    8.5
1     Bruno Lima    7.2
2   Carla Mendes    9.1
3   Daniel Rocha    6.8
4  Eduarda Alves    8.9

In [165]:
df.tail()

               Nome  Media
5      Felipe Costa    5.7
6  Gabriela Martins    9.5
7    Henrique Silva    7.9
8  Isabela Ferreira    8.3
9      João Pereira    6.4

Desafio:

1. Criar um arquivo .txt a partir de uma lista de perguntas vindas de uma lista em Python.
2. Ler as perguntas desse arquivo .txt e salva las em python
3. obter resposta de um LLM para cada uma
4. Salvar os resultados em um novo arquivo .csv
5. Ler os arquivos .csv usando Pandas

In [168]:
#Etapa 1
lista_de_perguntas = [
    "De que e feito e sol",
    "De que e feito o planeta saturno",
    "De que e feito o planeta terra",
    "De que e feito o planeta marte",
    "De que e feito o planeta venus",
    "De que e feito o planeta mercurio",
    "De que e feito o planeta urano",
    "Qual a galaxia mais aniga ja encontrada",
    "Qual a maior estrela ja encontrada",
    "Qual a estrela mais proxima do sol"
]

with open("perguntas.txt", "w", encoding="utf-8") as arquivos:
  for pergunta in lista_de_perguntas:
    arquivos.write(pergunta + "\n")

In [169]:
# Etapa 2

lista_desafio = []
with open("perguntas.txt", "r", encoding="utf-8" ) as arquivo:
     for linha in arquivo:
      lista_desafio.append(linha.strip())

      print(lista_desafio)

['De que e feito e sol']
['De que e feito e sol', 'De que e feito o planeta saturno']
['De que e feito e sol', 'De que e feito o planeta saturno', 'De que e feito o planeta terra']
['De que e feito e sol', 'De que e feito o planeta saturno', 'De que e feito o planeta terra', 'De que e feito o planeta marte']
['De que e feito e sol', 'De que e feito o planeta saturno', 'De que e feito o planeta terra', 'De que e feito o planeta marte', 'De que e feito o planeta venus']
['De que e feito e sol', 'De que e feito o planeta saturno', 'De que e feito o planeta terra', 'De que e feito o planeta marte', 'De que e feito o planeta venus', 'De que e feito o planeta mercurio']
['De que e feito e sol', 'De que e feito o planeta saturno', 'De que e feito o planeta terra', 'De que e feito o planeta marte', 'De que e feito o planeta venus', 'De que e feito o planeta mercurio', 'De que e feito o planeta urano']
['De que e feito e sol', 'De que e feito o planeta saturno', 'De que e feito o planeta terra', 'De que e feito o planeta marte', 'De que e feito o planeta venus', 'De que e feito o planeta mercurio', 'De que e feito o planeta urano', 'Qual a galaxia mais aniga ja encontrada']
['De que e feito e sol', 'De que e feito o planeta saturno', 'De que e feito o planeta terra', 'De que e feito o planeta marte', 'De que e feito o planeta venus', 'De que e feito o planeta mercurio', 'De que e feito o planeta urano', 'Qual a galaxia mais aniga ja encontrada', 'Qual a maior estrela ja encontrada']
['De que e feito e sol', 'De que e feito o planeta saturno', 'De que e feito o planeta terra', 'De que e feito o planeta marte', 'De que e feito o planeta venus', 'De que e feito o planeta mercurio', 'De que e feito o planeta urano', 'Qual a galaxia mais aniga ja encontrada', 'Qual a maior estrela ja encontrada', 'Qual a estrela mais proxima do sol']

In [172]:
lista_de_dicionarios_de_respostas = []

for pergunta in lista_desafio:
  resposta = gemini_model.generate_content(
      contents=f"Gere uma resposta muito sucinta para a pergunta {pergunta}"
  )

  lista_de_dicionarios_de_respostas.append({"pergunta": pergunta, "resposta": resposta.text})

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.0-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 557.71ms

TooManyRequests: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-2.0-flash
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-2.0-flash
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-2.0-flash
Please retry in 51.78946496s.

In [173]:
lista_de_dicionarios_de_respostas

[]

In [174]:
with open("respostas1.csv", "w", encoding="utf-8") as arquivo:
     arquivo.write("pergunta,resposta\n")
     for pergunta_dict in lista_de_dicionarios_de_respostas:
      arquivo.write(f"{pergunta_dict['pergunta']}, {pergunta_dict['resposta']}\n")

In [175]:
df_perguntas_e_respostas = pd.DataFrame(lista_de_dicionarios_de_respostas)

In [176]:
df_perguntas_e_respostas.to_csv("resposta2.csv", index=False, encoding="utf-8")

In [178]:
# Etapa 5

novo_df = pd.read_csv("resposta2.csv")

EmptyDataError: No columns to parse from file

In [179]:
novo_df

NameError: name 'novo_df' is not defined